# ================================
# Site Settings
# ================================
title: T O L E R A N Z B I E N E
logo: "/assets/images/logo.svg"
name: VT RLP
description: >
  Der Toleranzbegriff umfasst die unterschiedlichen Ausprägungen des Zuchtweges hin zur Varroaresistenz. Von ersten Anzeichen einer Idee gegen die Varroa im Bienenvolk bis hin zur Varroaresistenz, bei der auf alle Behandlung verzichtet werden kann, ist ein entsprechend langer Weg. Der Herausforderung haben wir uns als Varroatolerante Biene Rheinland-Pfalz e. V. gestellt.

#url: "https://hz80.github.io"
#baseurl: "/Website-toleranzbiene.de"

url: "https://www.toleranzbiene.de/"
baseurl: ""

repository:   # optional: username/repo (für GitHub Pages)

# ================================
# Theme
# ================================
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: air

# Skin (farbschema)
minimal_mistakes_skin: sunrise
# Alternativen: dark, air, aqua, contrast, neon, mint, sunrise

# ================================
# Plugins
# ================================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

search: false

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/toleranzbiene"
    - label: "Impressum"
      url: "./impressum/"

# Externe Links automatisch in neuem Tab öffnen
external_links:
  target: "_blank"
  rel: "noopener noreferrer"

# ================================
# Author (wichtig für Sidebar & Profile)
# ================================
author:
  name: "Varroatolerante Biene Rheinland-Pfalz e.V."
  bio: "Imkerei, Varroa-Resistenz und Biotechnik"
  location: "Deutschland"
  avatar: "/assets/images/avatar.png"   # optional
  logo: "/assets/images/logo.png"
  links:
    - label: "Instagram"
      icon: "fab fa-github"
      url: "https://instagram.com/toleranzbiene"

# ================================
# Defaults (extrem wichtig!)
# ================================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single

# ================================
# Markdown / Build
# ================================
markdown: kramdown
highlighter: rouge
# ================================
# Excludes
# ================================
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

atom_feed:
  hide: true
